### ISSUE TITLE
Plenty of FutureWarnings

### ISSUE THREAD

**Issue by jjlatval** [erwanm/TreeTaggerWrapper#1]
Hello.

I am using TreeTaggerWrapper in my NLP project. There are multiple FutureWarnings that were generated when running unittests for my projects. Most of the FutureWarnings are related to regexp, while one is related to SafeConfigParser being renamed ConfigParser and it will be removed in future versions. Below is the list of FutureWarnings generated during my unittest run (there most likely are many more warnings):

> venv/lib/python3.7/site-packages/treetaggerwrapper.py:544
>   /home/joni/ta_nlp/venv/lib/python3.7/site-packages/treetaggerwrapper.py:544: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
>     g_config = configparser.SafeConfigParser()
> 
> venv/lib/python3.7/site-packages/treetaggerwrapper.py:740
>   /home/joni/ta_nlp/venv/lib/python3.7/site-packages/treetaggerwrapper.py:740: FutureWarning: Possible nested set at position 8
>     re.IGNORECASE | re.VERBOSE)
> 
> venv/lib/python3.7/site-packages/treetaggerwrapper.py:2044
>   /home/joni/ta_nlp/venv/lib/python3.7/site-packages/treetaggerwrapper.py:2044: FutureWarning: Possible nested set at position 152
>     re.VERBOSE | re.IGNORECASE)
> 
> venv/lib/python3.7/site-packages/treetaggerwrapper.py:2067
>   /home/joni/ta_nlp/venv/lib/python3.7/site-packages/treetaggerwrapper.py:2067: FutureWarning: Possible nested set at position 409
>     UrlMatch_re = re.compile(UrlMatch_expression, re.VERBOSE | re.IGNORECASE)
> 
> venv/lib/python3.7/site-packages/treetaggerwrapper.py:2079
>   /home/joni/ta_nlp/venv/lib/python3.7/site-packages/treetaggerwrapper.py:2079: FutureWarning: Possible nested set at position 192
>     EmailMatch_re = re.compile(EmailMatch_expression, re.VERBOSE | re.IGNORECASE)

**Comment by erwanm** [comment]
Not the same TreeTagger wrapper :)
